on:
    release:
        types: [created]

permissions:
    contents: write
    packages: write

jobs:
    releases-matrix:
        name: Release the game
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, windows]
                goarch: ['386', amd64]
        steps:
            - uses: actions/checkout@v4
            - uses: wangyoucao577/go-release-action@v1
              with:
                goversion: "https://dl.google.com/go/go1.21.3.linux-amd64.tar.gz"
                github_token: ${{ secrets.GITHUB_TOKEN }}
                goos: ${{ matrix.goos }}
                goarch: ${{ matrix.goarch }}
                binary_name: 'shoot-run'
